server:
  port: 8081

#H2 settings
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

axon:
  amqp:
    exchange: bank-account.events
  eventhandling:
    processors:
      amqpEvents:
        source: complaintEventsMethod